const count=document.getElementById('count'),box=document.getElementById('voices'),status=document.getElementById('status'),tabSelect=document.getElementById('tab');let allVoices=[];
function prettyVoice(v){let n=String(v.name||'Voice').replace(/[_-][a-z]{2}([_-][A-Z]{2})?$/,'').replace(/\s+/g,' ').trim();try{const l=new Intl.Locale(String(v.lang||'').replace('_','-'));const dnL=new Intl.DisplayNames(['en'],{type:'language'}),dnR=new Intl.DisplayNames(['en'],{type:'region'});const lang=dnL.of(l.language),country=l.region?dnR.of(l.region):'';return [n,lang,country].filter(Boolean).join(' · ');}catch(e){return n;}}
function loadVoices(){allVoices=speechSynthesis.getVoices();render();}
function render(){const n=Number(count.value);box.innerHTML='';for(let i=0;i<n;i++){const row=document.createElement('div');row.className='voice';const label=document.createElement('label');label.textContent=String.fromCharCode(65+i);const sel=document.createElement('select');allVoices.forEach((v,j)=>{const o=document.createElement('option');o.value=j;o.textContent=prettyVoice(v);if(j===i)o.selected=true;sel.appendChild(o);});row.append(label,sel);box.appendChild(row);}}
async function loadTabs(){const tabs=await chrome.tabs.query({});const old=Number(tabSelect.value);tabSelect.innerHTML='';tabs.filter(t=>/^https?:/i.test(t.url||'')).forEach(t=>{const o=document.createElement('option');o.value=t.id;o.textContent=(t.active?'● ':'')+(t.title||t.url||('Tab '+t.id));if(t.active||t.id===old)o.selected=true;tabSelect.appendChild(o);});}
async function target(){const id=Number(tabSelect.value);return id||null;}
async function send(msg){const id=await target();if(!id)throw new Error('Choose a webpage tab.');return chrome.tabs.sendMessage(id,msg);}
count.onchange=render;speechSynthesis.onvoiceschanged=loadVoices;document.getElementById('refresh').onclick=loadVoices;document.getElementById('tabs').onclick=loadTabs;
document.getElementById('stop').onclick=async()=>{try{await send({type:'RR_STOP'});status.textContent='Stopped.';}catch(e){status.textContent=e.message;}};
document.getElementById('read').onclick=async()=>{const narrators=[...box.querySelectorAll('select')].map(s=>{const v=allVoices[Number(s.value)];return v?{name:v.name,lang:v.lang}:null;}).filter(Boolean);try{const r=await send({type:'RR_START',narrators,sectionSize:3});status.textContent=r?.message||'Reading started.';}catch(e){status.textContent='Open/reload that tab, then try again.';}};
loadVoices();loadTabs();