const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let mode='tab',allVoices=[],fileText='',fileTitle='';const AFRICA=new Set(['DZ','AO','BJ','BW','BF','BI','CM','CV','CF','TD','KM','CD','CG','CI','DJ','EG','GQ','ER','SZ','ET','GA','GM','GH','GN','GW','KE','LS','LR','LY','MG','MW','ML','MR','MU','MA','MZ','NA','NE','NG','RW','ST','SN','SC','SL','SO','ZA','SS','SD','TZ','TG','TN','UG','ZM','ZW']);
function info(v){let locale=String(v.lang||'').replace('_','-'),lang='',country='',region='';try{let l=new Intl.Locale(locale);region=l.region||'';let dl=new Intl.DisplayNames(['en'],{type:'language'}),dr=new Intl.DisplayNames(['en'],{type:'region'});lang=dl.of(l.language)||l.language;country=region?(dr.of(region)||region):''}catch(e){lang=locale}let raw=String(v.name||'Voice'),name=raw.replace(/^Microsoft\s+/i,'').replace(/\s+Online.*$/i,'').replace(/Neural$/i,'').replace(/[_-](?:[a-z]{2,3})(?:[_-][A-Z]{2})?.*$/,'').trim()||'Voice';let lower=raw.toLowerCase(),group=/multilingual/i.test(raw)?'Multilingual':/^en\b/i.test(locale)?'English':/^(zh|yue)\b/i.test(locale)?'Chinese':AFRICA.has(region)?'African':/^es\b/i.test(locale)?'Spanish':lang||'Other';return{name,country,lang,region,group,label:[name,country].filter(Boolean).join(' · ')}}
const order=g=>({Multilingual:0,English:1,Chinese:2,African:3,Spanish:4}[g]??10);
function loadVoices(){allVoices=speechSynthesis.getVoices();renderVoices()}
function renderVoices(){let n=Number($('#count').value),selected=$$('#voices select').map(x=>x.value);$('#voices').innerHTML='';for(let slot=0;slot<n;slot++){let groups={};allVoices.forEach((v,i)=>{let x=info(v);(groups[x.group]??=[]).push({v,i,x})});Object.keys(groups).sort((a,b)=>order(a)-order(b)||a.localeCompare(b)).forEach(g=>groups[g].sort((a,b)=>a.x.country.localeCompare(b.x.country)||a.x.name.localeCompare(b.x.name)));let wrap=document.createElement('div');wrap.className='voice-group';let h=document.createElement('h3');h.textContent=String.fromCharCode(65+slot)+' · Voice';wrap.append(h);let sel=document.createElement('select');Object.keys(groups).sort((a,b)=>order(a)-order(b)||a.localeCompare(b)).forEach(g=>{let og=document.createElement('optgroup');og.label=g;groups[g].forEach(({i,x})=>{let o=document.createElement('option');o.value=i;o.textContent=x.label;o.title=[x.lang,x.country].filter(Boolean).join(' · ');og.append(o)});sel.append(og)});sel.value=selected[slot]??String(slot);wrap.append(sel);$('#voices').append(wrap)}}
async function loadTabs(){let tabs=await chrome.tabs.query({});$('#tab').innerHTML='';tabs.filter(t=>/^https?:/i.test(t.url||'')).forEach(t=>{let o=document.createElement('option');o.value=t.id;o.textContent=(t.active?'● ':'')+(t.title||t.url);if(t.active)o.selected=true;$('#tab').append(o)});tabTools()}
function tabTools(){let o=$('#tab').selectedOptions[0],t=(o?.textContent||'').toLowerCase();$('#tabTools').innerHTML=t.includes('youtube')?'<span class="muted">YouTube: Reader will try to open and extract the transcript automatically.</span>':t.includes('google docs')?'<span class="muted">Google Docs: Reader will try direct document export, then page fallbacks.</span>':''}
async function send(msg){let id=Number($('#tab').value);if(!id)throw Error('Choose a webpage tab.');return chrome.tabs.sendMessage(id,msg)}
$$('.sources button').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;$$('.sources button').forEach(x=>x.classList.toggle('on',x===b));['tab','paste','file'].forEach(x=>$('#'+x+'Pane').hidden=x!==mode)});
$('#count').onchange=renderVoices;$('#refresh').onclick=loadVoices;$('#tabs').onclick=loadTabs;$('#tab').onchange=tabTools;speechSynthesis.onvoiceschanged=loadVoices;
$('#file').onchange=async e=>{let f=e.target.files[0];if(!f)return;fileTitle=f.name;$('#fileName').textContent=f.name;try{if(/pdf/i.test(f.type)||/\.pdf$/i.test(f.name)){let data=await f.arrayBuffer(),pdf=await pdfjsLib.getDocument({data}).promise,p=[];for(let i=1;i<=pdf.numPages;i++){let page=await pdf.getPage(i),tc=await page.getTextContent();p.push(tc.items.map(x=>x.str).join(' '))}fileText=p.join('\n\n')}else fileText=await f.text();$('#status').textContent='Loaded '+f.name}catch(err){$('#status').textContent='File error: '+err.message}};
$('#stop').onclick=()=>send({type:'RR_STOP'}).catch(()=>{});
$('#read').onclick=async()=>{let ns=$$('#voices select').map(s=>{let v=allVoices[Number(s.value)];return v?{name:v.name,lang:v.lang}:null}).filter(Boolean);try{if(mode==='tab'){let r=await send({type:'RR_START',narrators:ns,sectionSize:3});$('#status').textContent=r.message}else{let text=mode==='paste'?$('#paste').value:fileText;if(!text.trim())throw Error('Add some text first.');let [tab]=await chrome.tabs.query({active:true,currentWindow:true});let r=await chrome.tabs.sendMessage(tab.id,{type:'RR_READ_TEXT',text,title:mode==='file'?fileTitle:'Pasted text',narrators:ns,sectionSize:3});$('#status').textContent=r.message}}catch(e){$('#status').textContent=e.message||'Reload the target tab and try again.'}};
loadVoices();loadTabs();